Import Upstream version 011+36+gd727c5a

diff --git a/modules.d/99base/init b/modules.d/99base/init
--- a/modules.d/99base/init
+++ b/modules.d/99base/init
@@ -1,116 +1,173 @@
 #!/bin/sh
+# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
+# ex: ts=8 sw=4 sts=4 et filetype=sh
 #
 # Licensed under the GPLv2
 #
-# Copyright 2008-2009, Red Hat, Inc.
+# Copyright 2008-2010, Red Hat, Inc.
 # Harald Hoyer <harald@redhat.com>
 # Jeremy Katz <katzj@redhat.com>
 
 wait_for_loginit()
 {
-    if getarg rdinitdebug; then
-	set +x
-	exec 1>- 2>-
-	exec 0<>/dev/console 1<>/dev/console 2<>/dev/console
-	# wait for loginit
-	i=0
-	while [ $i -lt 10 ]; do 
-	    j=$(jobs)
-	    [ -z "$j" ] && break
-	    [ -z "${j##*Running*}" ] || break
-	    sleep 0.1
-	    i=$(($i+1))
-	done	
-	[ $i -eq 10 ] && kill %1 >/dev/null 2>&1
+    set +x
+    [ "$RD_DEBUG" = "yes" ] || return
+    [ -e /run/initramfs/loginit.pipe ] || return
+    echo "DRACUT_LOG_END"
+    exec 0<>/dev/console 1<>/dev/console 2<>/dev/console
+        # wait for loginit
+    i=0
+    while [ $i -lt 10 ]; do
+        if [ ! -e /run/initramfs/loginit.pipe ]; then
+            j=$(jobs)
+            [ -z "$j" ] && break
+            [ -z "${j##*Running*}" ] || break
+        fi
+        sleep 0.1
+        i=$(($i+1))
+    done
 
-        while pidof -x /sbin/loginit >/dev/null 2>&1; do
-            for pid in $(pidof -x /sbin/loginit); do
-                kill $HARD $pid >/dev/null 2>&1
-            done
-            HARD="-9"
-        done
-	set -x
+    if [ $i -eq 10 ]; then
+        kill %1 >/dev/null 2>&1
+        kill $(while read line;do echo $line;done</run/initramfs/loginit.pid)
     fi
+
+    set -x
+    rm -f /run/initramfs/loginit.pipe /run/initramfs/loginit.pid
 }
 
 emergency_shell()
 {
+    set +e
     if [ "$1" = "-n" ]; then
         _rdshell_name=$2
-        shift 2 
+        shift 2
     else
         _rdshell_name=dracut
     fi
-    wait_for_loginit
     echo ; echo
-    echo $@
-    source_all emergency
+    warn $@
+    source_hook emergency
     echo
-    if getarg rdshell || getarg rdbreak; then
+    wait_for_loginit
+    [ -e /run/initramfs/.die ] && exit 1
+    if getargbool 1 rd.shell -y rdshell || getarg rd.break rdbreak; then
         echo "Dropping to debug shell."
         echo
         export PS1="$_rdshell_name:\${PWD}# "
         [ -e /.profile ] || echo "exec 0<>/dev/console 1<>/dev/console 2<>/dev/console" > /.profile
         sh -i -l
     else
-        echo "Boot has failed, sleeping forever."
-        while :; do sleep 365d;done
+        warn "Boot has failed. To debug this issue add \"rdshell\" to the kernel command line."
+        # cause a kernel panic
+        exit 1
     fi
 }
 
-export PATH=/sbin:/bin:/usr/sbin:/usr/bin
-export TERM=linux
 NEWROOT="/sysroot"
+[ -d $NEWROOT ] || mkdir -p -m 0755 $NEWROOT
 
 trap "emergency_shell Signal caught!" 0
+OLDPATH=$PATH
+PATH=/usr/sbin:/usr/bin:/sbin:/bin
+export PATH
 
-RDDEBUG=""
+RD_DEBUG=""
 . /lib/dracut-lib.sh
 
-mknod /dev/null c 1 3
+[ -c /dev/null ] || mknod -m 0666 /dev/null c 1 3
 
 # mount some important things
-mount -t proc /proc /proc >/dev/null 2>&1
-mount -t sysfs /sys /sys >/dev/null 2>&1
+[ ! -d /proc/self ] && \
+    mount -t proc -o nosuid,noexec,nodev proc /proc >/dev/null 2>&1
 
-if [ ! -c /dev/ptmx ]; then
-    # try to mount devtmpfs
-    if ! mount -t devtmpfs -omode=0755 udev /dev >/dev/null 2>&1; then
-        # if it failed fall back to normal tmpfs
-	mount -t tmpfs -omode=0755 udev /dev >/dev/null 2>&1 
-	# Make some basic devices first, let udev handle the rest
-	mknod /dev/null c 1 3
-	mknod /dev/ptmx c 5 2
-	mknod /dev/console c 5 1
-	mknod /dev/kmsg c 1 11
-    fi
+[ ! -d /sys/kernel ] && \
+    mount -t sysfs -o nosuid,noexec,nodev sysfs /sys >/dev/null 2>&1
+
+SECURITYFSDIR="/sys/kernel/security"
+export SECURITYFSDIR
+if ! ismounted "${SECURITYFSDIR}"; then
+    mount -t securityfs -o nosuid,noexec,nodev ${SECURITYFSDIR} ${SECURITYFSDIR} >/dev/null 2>&1
 fi
 
-ln -s /proc/self/fd /dev/fd >/dev/null 2>&1
-
-if getarg rdinitdebug; then
-    getarg quiet && DRACUT_QUIET="yes"
-    mkfifo /dev/initlog.pipe
-    /sbin/loginit $DRACUT_QUIET </dev/initlog.pipe >/dev/console 2>&1 &
-    exec >/dev/initlog.pipe 2>&1
+if [ -x /lib/systemd/systemd-timestamp ]; then
+    RD_TIMESTAMP=$(/lib/systemd/systemd-timestamp)
 else
-    exec 0<>/dev/console 1<>/dev/console 2<>/dev/console
+    read RD_TIMESTAMP _tmp < /proc/uptime
+    unset _tmp
 fi
 
 setdebug
 
-mkdir /dev/shm
-mkdir /dev/pts
-mount -t devpts -o gid=5,mode=620 devpts /dev/pts >/dev/null 2>&1
-mount -t tmpfs tmpfs /dev/shm >/dev/null 2>&1
+if [ "$RD_DEBUG" = "yes" ]; then
+    getarg quiet && DRACUT_QUIET="yes"
+    a=$(getarg loglevel=)
+    [ -n "$a" ] && [ $a -ge 8 ] && unset DRACUT_QUIET
+fi
+
+if ! ismounted /dev; then
+    # try to mount devtmpfs
+    if ! mount -t devtmpfs -o mode=0755,nosuid devtmpfs /dev >/dev/null 2>&1; then
+        # if it failed fall back to normal tmpfs
+        mount -t tmpfs -o mode=0755,nosuid tmpfs /dev >/dev/null 2>&1
+        # Make some basic devices first, let udev handle the rest
+        mknod -m 0666 /dev/null c 1 3
+        mknod -m 0666 /dev/ptmx c 5 2
+        mknod -m 0600 /dev/console c 5 1
+        mknod -m 0660 /dev/kmsg c 1 11
+    fi
+fi
+
+# prepare the /dev directory
+[ ! -h /dev/fd ] && ln -s /proc/self/fd /dev/fd >/dev/null 2>&1
+[ ! -h /dev/stdin ] && ln -s /proc/self/fd/0 /dev/stdin >/dev/null 2>&1
+[ ! -h /dev/stdout ] && ln -s /proc/self/fd/1 /dev/stdout >/dev/null 2>&1
+[ ! -h /dev/stderr ] && ln -s /proc/self/fd/2 /dev/stderr >/dev/null 2>&1
+
+if ! ismounted /dev/pts; then
+    mkdir -m 0755 /dev/pts
+    mount -t devpts -o gid=5,mode=620,noexec,nosuid devpts /dev/pts >/dev/null 2>&1
+fi
+
+if ! ismounted /dev/shm; then
+    mkdir -m 0755 /dev/shm
+    mount -t tmpfs -o mode=1777,nosuid,nodev tmpfs /dev/shm >/dev/null 2>&1
+fi
+
+if ! ismounted /run; then
+    mkdir -m 0755 /newrun
+    mount -t tmpfs -o mode=0755,nosuid,nodev tmpfs /newrun >/dev/null 2>&1
+    cp -a -t /newrun /run/*
+    mount --move /newrun /run
+    rm -fr /newrun
+fi
+
+[ -d /run/initramfs ] || mkdir -p -m 0755 /run/initramfs
 
 UDEVVERSION=$(udevadm --version)
+if [ $UDEVVERSION -gt 166 ]; then
+    # newer versions of udev use /run/udev/rules.d
+    export UDEVRULESD=/run/udev/rules.d
+    [ -d /run/udev ] || mkdir -p -m 0755 /run/udev
+    [ -d $UDEVRULESD ] || mkdir -p -m 0755 $UDEVRULESD
+else
+    mkdir -m 0755 /dev/.udev /dev/.udev/rules.d
+    export UDEVRULESD=/dev/.udev/rules.d
+fi
+
+if [ "$RD_DEBUG" = "yes" ]; then
+    mkfifo /run/initramfs/loginit.pipe
+    loginit $DRACUT_QUIET </run/initramfs/loginit.pipe >/dev/console 2>&1 &
+    exec >/run/initramfs/loginit.pipe 2>&1
+else
+    exec 0<>/dev/console 1<>/dev/console 2<>/dev/console
+fi
 
 source_conf /etc/conf.d
 
 # run scriptlets to parse the command line
-getarg 'rdbreak=cmdline' && emergency_shell -n cmdline "Break before cmdline"
-source_all cmdline
+getarg 'rd.break=cmdline' 'rdbreak=cmdline' && emergency_shell -n cmdline "Break before cmdline"
+source_hook cmdline
 
 [ -z "$root" ] && die "No or empty root= argument"
 [ -z "$rootok" ] && die "Don't know how to handle 'root=$root'"
@@ -126,8 +183,8 @@ source_all cmdline
 } > /tmp/root.info
 
 # pre-udev scripts run before udev starts, and are run only once.
-getarg 'rdbreak=pre-udev' && emergency_shell -n pre-udev "Break before pre-udev"
-source_all pre-udev
+getarg 'rd.break=pre-udev' 'rdbreak=pre-udev' && emergency_shell -n pre-udev "Break before pre-udev"
+source_hook pre-udev
 
 # start up udev and trigger cold plugs
 udevd --daemon --resolve-names=never
@@ -136,47 +193,48 @@ UDEV_LOG_PRIO_ARG=--log-priority
 UDEV_QUEUE_EMPTY="udevadm settle --timeout=0"
 
 if [ $UDEVVERSION -lt 140 ]; then
-   UDEV_LOG_PRIO_ARG=--log_priority
-   UDEV_QUEUE_EMPTY="udevadm settle --timeout=1"
+    UDEV_LOG_PRIO_ARG=--log_priority
+    UDEV_QUEUE_EMPTY="udevadm settle --timeout=1"
 fi
 
-getarg rdudevinfo && udevadm control $UDEV_LOG_PRIO_ARG=info
-getarg rdudevdebug && udevadm control $UDEV_LOG_PRIO_ARG=debug
+getargbool 0 rd.udev.info -y rdudevinfo && udevproperty "$UDEV_LOG_PRIO_ARG=info"
+getargbool 0 rd.udev.debug -y rdudevdebug && udevproperty "$UDEV_LOG_PRIO_ARG=debug"
+udevproperty "hookdir=$hookdir"
 
-getarg 'rdbreak=pre-trigger' && emergency_shell -n pre-trigger "Break before pre-trigger"
-source_all pre-trigger
+getarg 'rd.break=pre-trigger' 'rdbreak=pre-trigger' && emergency_shell -n pre-trigger "Break before pre-trigger"
+source_hook pre-trigger
 
 # then the rest
-udevadm trigger $udevtriggeropts  >/dev/null 2>&1
+udevadm trigger --action=add $udevtriggeropts  >/dev/null 2>&1
 
-getarg 'rdbreak=initqueue' && emergency_shell -n initqueue "Break before initqueue"
+getarg 'rd.break=initqueue' 'rdbreak=initqueue' && emergency_shell -n initqueue "Break before initqueue"
+
+RDRETRY=$(getarg rd.retry 'rd_retry=')
+RDRETRY=${RDRETRY:-20}
+RDRETRY=$(($RDRETRY*2))
 
 i=0
 while :; do
 
     check_finished && break
- 
+
     udevsettle
 
     check_finished && break
 
-    if [ -f /initqueue/work ]; then
-        rm /initqueue/work
+    if [ -f $hookdir/initqueue/work ]; then
+        rm $hookdir/initqueue/work
     fi
-    	
-    for job in /initqueue/*.sh; do
-	[ -e "$job" ] || break
+
+    for job in $hookdir/initqueue/*.sh; do
+        [ -e "$job" ] || break
         job=$job . $job
         check_finished && break 2
     done
 
     $UDEV_QUEUE_EMPTY >/dev/null 2>&1 || continue
 
-    modprobe scsi_wait_scan && rmmod scsi_wait_scan
-
-    $UDEV_QUEUE_EMPTY >/dev/null 2>&1 || continue
-
-    for job in /initqueue-settled/*.sh; do
+    for job in $hookdir/initqueue/settled/*.sh; do
         [ -e "$job" ] || break
         job=$job . $job
         check_finished && break 2
@@ -186,28 +244,57 @@ while :; do
 
     # no more udev jobs and queues empty.
     sleep 0.5
+
+    # dirty hack for some cdrom drives,
+    # which report no medium for quiet
+    # some time.
+    for cdrom in /sys/block/sr*; do
+        [ -e "$cdrom" ] || continue
+        # skip, if cdrom medium was already found
+        strstr "$(udevadm info --query=env --path=${cdrom##/sys})" \
+            ID_CDROM_MEDIA && continue
+
+        if [ -e "$cdrom"/events_poll_msecs -a ! -e "/tmp/.poll_${cdrom##*/}" ]; then
+            msecs=$(while read a; do echo $a;done < "$cdrom"/events_poll_msecs)
+            if [ "$msecs" = "-1" ]; then
+                echo 250 > "$cdrom"/events_poll_msecs
+                > "/tmp/.poll_${cdrom##*/}"
+            fi
+        else
+            echo change > "$cdrom/uevent"
+        fi
+    done
+
     i=$(($i+1))
-    [ $i -gt 20 ] \
-        && { flock -s 9 ; emergency_shell "No root device found"; } 9>/.console_lock
+    [ $i -gt $RDRETRY ] \
+        && { flock -s 9 ; emergency_shell "No root device \"$root\" found"; } 9>/.console_lock
 done
 unset job
 unset queuetriggered
 
+# reset cdrom polling
+for cdrom in /sys/block/sr*; do
+    [ -e "$cdrom" ] || continue
+    if [ -e "$cdrom"/events_poll_msecs ]; then
+        echo -1 > "$cdrom"/events_poll_msecs
+    fi
+done
+
 # pre-mount happens before we try to mount the root filesystem,
 # and happens once.
-getarg 'rdbreak=pre-mount' && emergency_shell -n pre-mount "Break pre-mount"
-source_all pre-mount
+getarg 'rd.break=pre-mount' 'rdbreak=pre-mount' && emergency_shell -n pre-mount "Break pre-mount"
+source_hook pre-mount
 
 
-getarg 'rdbreak=mount' && emergency_shell -n mount "Break mount"
+getarg 'rd.break=mount' 'rdbreak=mount' && emergency_shell -n mount "Break mount"
 # mount scripts actually try to mount the root filesystem, and may
 # be sourced any number of times. As soon as one suceeds, no more are sourced.
 i=0
 while :; do
     [ -d "$NEWROOT/proc" ] && break;
-    for f in /mount/*.sh; do
-       [ -f "$f" ] && . "$f"
-       [ -d "$NEWROOT/proc" ] && break;
+    for f in $hookdir/mount/*.sh; do
+        [ -f "$f" ] && . "$f"
+        [ -d "$NEWROOT/proc" ] && break;
     done
 
     i=$(($i+1))
@@ -217,17 +304,44 @@ done
 
 {
     echo -n "Mounted root filesystem "
-    while read dev mp rest; do [ "$mp" = "$NEWROOT" ] && echo $dev; done < /proc/mounts 
+    while read dev mp rest; do [ "$mp" = "$NEWROOT" ] && echo $dev; done < /proc/mounts
 } | vinfo
 
 # pre pivot scripts are sourced just before we switch over to the new root.
-getarg 'rdbreak=pre-pivot' && emergency_shell -n pre-pivot "Break pre-pivot"
-source_all pre-pivot
+getarg 'rd.break=pre-pivot' 'rdbreak=pre-pivot' && emergency_shell -n pre-pivot "Break pre-pivot"
+source_hook pre-pivot
 
 # by the time we get here, the root filesystem should be mounted.
-# Try to find init.
-for i in "$(getarg init=)" /sbin/init /etc/init /init /bin/sh; do
-    [ -f "$NEWROOT$i" -a -x "$NEWROOT$i" ] && { INIT="$i"; break; }
+# Try to find init and mount /usr, if needed to access init.
+unset __usr_found
+for i in "$(getarg real_init=)" "$(getarg init=)" /sbin/init /etc/init /init /bin/sh; do
+    [ -n "$i" ] || continue
+
+    __p=$(readlink -m "$NEWROOT$i")
+    if [ -n "$__p" ] \
+        && [ "x$__usr_found" = "x" ] \
+        && [ ! -x "$__p" ] \
+        && strstr "$__p" "$NEWROOT/usr" \
+        ; then
+        # we have to mount /usr
+        while read dev mp fs opts rest; do
+            if [ "$mp" = "/usr" ]; then
+                echo "$dev $NEWROOT$mp $fs ${opts},ro $rest"
+                __usr_found="1"
+                break
+            fi
+        done < "$NEWROOT/etc/fstab" >> /etc/fstab
+        if [ "x$__usr_found" != "x" ]; then
+            info "Mounting /usr"
+            mount "$NEWROOT/usr" 2>&1 | vinfo
+        fi
+    fi
+
+    __p=$(readlink -f "$NEWROOT$i")
+    if [ -x "$__p" ]; then
+        INIT="$i"
+        break
+    fi
 done
 
 [ "$INIT" ] || {
@@ -236,69 +350,114 @@ done
     emergency_shell
 }
 
-getarg rdbreak && emergency_shell -n switch_root "Break before switch_root"
+getarg rd.break rdbreak && emergency_shell -n switch_root "Break before switch_root"
 
-# stop udev queue before killing it
-udevadm control --stop-exec-queue
+if [ $UDEVVERSION -lt 168 ]; then
+    # stop udev queue before killing it
+    udevadm control --stop-exec-queue
 
-HARD=""
-while pidof udevd >/dev/null 2>&1; do 
-    for pid in $(pidof udevd); do
-	kill $HARD $pid >/dev/null 2>&1
+    HARD=""
+    while pidof udevd >/dev/null 2>&1; do
+        for pid in $(pidof udevd); do
+            kill $HARD $pid >/dev/null 2>&1
+        done
+        HARD="-9"
     done
-    HARD="-9"
-done
+else
+    udevadm control --exit
+    udevadm info --cleanup-db
+fi
 
+export RD_TIMESTAMP
+set +x # Turn off debugging for this section
 # Clean up the environment
 for i in $(export -p); do
     i=${i#declare -x}
     i=${i#export}
+    strstr "$i" "=" || continue
     i=${i%%=*}
-    [ "$i" = "root" -o "$i" = "PATH" -o "$i" = "HOME" -o "$i" = "TERM" ] || unset $i
+    [ -z "$i" ] && continue
+    case $i in
+        root|PATH|HOME|TERM|PS4|RD_*)
+            :;;
+        *)
+            unset "$i";;
+    esac
 done
 
 initargs=""
-
 read CLINE </proc/cmdline
 if getarg init= >/dev/null ; then
+    set +x # Turn off debugging for this section
     ignoreargs="console BOOT_IMAGE"
     # only pass arguments after init= to the init
     CLINE=${CLINE#*init=}
-    set $CLINE
-    shift
+    set -- $CLINE
+    shift # clear out the rest of the "init=" arg
     for x in "$@"; do
-        for s in $ignoreargs; do       
+        for s in $ignoreargs; do
             [ "${x%%=*}" = $s ] && continue 2
         done
         initargs="$initargs $x"
     done
     unset CLINE
 else
-    set $CLINE
-    shift
+    set +x # Turn off debugging for this section
+    set -- $CLINE
     for x in "$@"; do
         case "$x" in
-            [0-9]|s|S|single|emergency|auto )
+            [0-9]|s|S|single|emergency|auto ) \
                 initargs="$initargs $x"
-            ;;
+                ;;
         esac
     done
 fi
+[ "$RD_DEBUG" = "yes" ] && set -x
 
-# Debug: Copy state
-if getarg rdcopystate; then
-    mkdir /dev/.initramfs/
-    cp /tmp/* /dev/.initramfs/ >/dev/null 2>&1
+if [ -d "$NEWROOT"/run ]; then
+    NEWRUN="${NEWROOT}/run"
+    mount --bind /run "$NEWRUN"
+    NEWINITRAMFSROOT="$NEWRUN/initramfs"
+
+    if [ "$NEWINITRAMFSROOT/lib" -ef "/lib" ]; then
+        for d in bin etc lib lib64 sbin tmp usr var; do
+            [ -h /$d ] && ln -fsn $NEWINITRAMFSROOT/$d /$d
+        done
+    fi
+else
+    NEWRUN=/dev/.initramfs
+    mkdir -m 0755 "$NEWRUN"
+    mount --bind /run/initramfs "$NEWRUN"
 fi
-
-info "Switching root"
 
 wait_for_loginit
 
-exec switch_root "$NEWROOT" "$INIT" $initargs || {
-    echo "Something went very badly wrong in the initramfs.  Please "
-    echo "file a bug against dracut."
-    emergency_shell
-}
-# vim:ts=8:sw=4:sts=4:et
+info "Switching root"
 
+unset PS4
+
+CAPSH=$(command -v capsh)
+SWITCH_ROOT=$(command -v switch_root)
+PATH=$OLDPATH
+export PATH
+
+if [ -f /etc/capsdrop ]; then
+    . /etc/capsdrop
+    info "Calling $INIT with capabilities $CAPS_INIT_DROP dropped."
+    unset RD_DEBUG
+    exec $CAPSH --drop="$CAPS_INIT_DROP" -- \
+        -c "exec switch_root \"$NEWROOT\" \"$INIT\" $initargs" || \
+    {
+	warn "Command:"
+	warn capsh --drop=$CAPS_INIT_DROP -- -c exec switch_root "$NEWROOT" "$INIT" $initargs
+	warn "failed."
+	emergency_shell
+    }
+else
+    unset RD_DEBUG
+    exec $SWITCH_ROOT "$NEWROOT" "$INIT" $initargs || {
+	warn "Something went very badly wrong in the initramfs.  Please "
+	warn "file a bug against dracut."
+	emergency_shell
+    }
+fi
